### ISSUE TITLE
Suporte SqlLite e funciona Android ?

### ISSUE THREAD

**Issue by resultdesenv** [LinlindembergCz/DEntityFramework#2]
Suporte SqlLite e funciona Android ?

**Comment by LinlindembergCz** [comment]
Como é um projeto bem recente, o foco principal está sendo  SQLServer, FireBird, MySQL, PostGreSQL. Como o Framework é uma abstração do FireDac creio que seja possível utilizar em um ambiente android, no entanto, falta implementar a conexão SQLLite... o que não nada é complexo.
